version: "3.3"

services:
  app:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips='*'
    depends_on:
      - db
      - mongo

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=dnacd
      - POSTGRES_PASSWORD=12345678
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dnacd
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - "27017:27017"
    command: --quiet
    volumes:
      - ./data/mongo:/data/db
